### ISSUE TITLE
VFS: some files are shown in wrong tag directory

### ISSUE THREAD

**Issue by zod** [oniony/TMSU#27] opened 2015-02-22 19:40 UTC
If the name of a directory is numeric the file with the this fileId is shown in the directory as seen in the following example.
```shell
mkdir data
cd data
tmsu init
mkdir 1 2
echo a > 1/a
echo b > 1/b
echo c > 2/c
echo d > 2/d
tmsu tag --tags foo -r 1
tmsu tag --tags bar -r 2
mkdir ../mnt
tmsu mount ../mnt
cd ..
ls -al mnt/tags/bar
```
ls shows both files tagged with 'bar' but also file 'b' which doesn't have this tag. This happens because its fileId is '2' which is also the tagId of 'bar'.

**Comment by 0ion9** [comment] 2015-02-22 21:56
I'm not sure whether I agree with your explanation of *why* it's happening, but I can agree that I can successfully reproduce this problem.

**Comment by oniony** [comment] 2015-02-23 16:33
Thanks for reporting this. I'll try to have a look at this over the next few days.

**Comment by oniony** [comment] 2015-02-25 07:56
I have just tried to reproduce this (twice) and failed:

    paul@annie> mkdir inv                                                                                                   ~/test
    paul@annie> cd inv                                                                                                      ~/test
    paul@annie> ls                                                                                                      ~/test/inv
    paul@annie> tmsu init                                                                                               ~/test/inv
    tmsu: creating database at '/home/paul/test/inv/.tmsu/db'.
    paul@annie> mkdir 1 2                                                                                               ~/test/inv
    paul@annie> echo a >1/a                                                                                             ~/test/inv
    paul@annie> echo b >1/b                                                                                             ~/test/inv
    paul@annie> echo c >2/c                                                                                             ~/test/inv
    paul@annie> echo d >2/d                                                                                             ~/test/inv
    paul@annie> tmsu tag --tags=foo --recursive 1                                                                       ~/test/inv
    tmsu: New tag 'foo'.
    paul@annie> tmsu tag --tags=bar --recursive 2                                                                       ~/test/inv
    tmsu: New tag 'bar'.
    paul@annie> tmsu tags 1/a 1/b 2/c 2/d                                                                               ~/test/inv
    1/a: foo
    1/b: foo
    2/c: bar
    2/d: bar
    paul@annie> tmsu mount ../mp                                                                                        ~/test/inv
    paul@annie> ..                                                                                                      ~/test/inv
    paul@annie> ls mp/tags/foo                                                                                              ~/test
    1.1  a.3  b.2
    paul@annie> ls mp/tags/bar                                                                                              ~/test
    2.4  c.5  d.6

I'll have a look over the code but I cannot see, at present, how it could go wrong.

**Comment by 0ion9** [comment] 2015-02-25 08:11
I thought perhaps OP and I had misunderstood something, so I retried, following your procedure above. But the problem still occurs:

```
18 /tmp: ls mp/tags/foo -l
total 0
lrwxr-xr-x 1 kau kau 80 Feb 25 18:33 1.1 -> /tmp/inv/1
lrwxr-xr-x 1 kau kau  2 Feb 25 18:33 a.3 -> /tmp/inv/1/a
lrwxr-xr-x 1 kau kau  2 Feb 25 18:33 b.2 -> /tmp/inv/1/b

18 /tmp: ls mp/tags/bar -l
total 0
lrwxr-xr-x 1 kau kau 2 Feb 25 18:33 2.4 -> /tmp/inv/1/b
lrwxr-xr-x 1 kau kau 2 Feb 25 18:33 c.6 -> /tmp/inv/2/c
lrwxr-xr-x 1 kau kau 2 Feb 25 18:33 d.5 -> /tmp/inv/2/d
```

`bar/2.4 -> /tmp/inv/1/b` is plainly wrong: 1/b is not tagged bar, as `cd inv;tmsu tags 1/b` clearly shows.
Logically, it seems that `bar/2.4` ought to point to `/tmp/inv/2` rather than `/tmp/inv/1/b`.

**Comment by oniony** [comment] 2015-02-25 08:16
OK, as I cannot reproduce this I am guessing we are running different versions. Which commit are you compiled against?

**Comment by oniony** [comment] 2015-02-25 08:19
Many thanks for that. I didn't realise it was just the link target that was wrong. I have reproduced now. I'll get this fixed.

**Comment by oniony** [comment] 2015-02-25 08:45
Fixed in 4a671d2.

**Closed** 2015-02-25 08:45 UTC
Labels: bug

**Comment by zod** [comment] 2015-02-25 10:03
Sorry for the bad description and thank to @0ion9 for stepping in and thanks @oniony for fixing it quickly. Just confirmed that the link now has the correct target directory.

**Comment by oniony** [comment] 2015-02-25 11:22
All good, thanks again.
