### ISSUE TITLE
CLI Mount Pipe Issue

### ISSUE THREAD

**Issue by throwaway847834** [oniony/TMSU#156] opened 2018-11-16 06:59 UTC
I think there's a bug with this pipe: https://github.com/oniony/TMSU/blob/master/src/github.com/oniony/TMSU/cli/mount.go#L152

When I mount with `tmsu mount`, it spawns the vfs process with stderr pointing to a pipe. When I navigate to `tags/<tag>/files`, the program crashes with SIGPIPE. I think this is when it attempts to print "Unimplemented opcode INTERRUPT" to stderr. 

Running `tail -f /proc/<pid>/fd/2` makes it not crash when I navigate to that directory.

Running `tmsu vfs` directly spawns a process with stderr set to my terminal (or /dev/null) and doesn't crash. 

It seems like `tmsu mount` creates a pipe, closes it, `tmsu vfs` attempts to write to the closed pipe and dies.

**Comment by oniony** [comment] 2018-11-17 10:56
Thanks for reporting. I'll endeavour to take a look this weekend.

**Comment by oniony** [comment] 2018-11-28 21:47
I'm not able to reproduce this issue. Could you please provide a little more detail into which tags you are accessing and your thoughts on why you are getting this "unimplemented opcode INTERRUPT" error?

What platform are you on, for example?

**Comment by oniony** [comment] 2018-11-28 22:43
OK, I've managed to work out what is going on. You're getting an error, but it's unclear why, and the TMSU daemon process (`tmsu vfs`) is trying to write to the standard error, which is a broken pipe because the TMSU mount process (`tmsu mount`) has closed.

So I've tried a few things, such as closing the pipe before the mount process exits, and recovering from the panic when TMSU logs, but to no avail.

So, instead, I've decided to redirect the mount process to a temporary file instead.

**Comment by oniony** [comment] 2018-11-28 22:44
Fixed on master.

**Closed by oniony** 2018-11-28 22:44 UTC

**Comment by throwaway847834** [comment] 2018-12-18 19:52
Cool, thanks.

**Comment by dimgel** [comment] 2019-10-31 19:16
Can you please tag 0.7.5 including this fix?

**Comment by oniony** [comment] 2019-11-04 10:03
Sorry, busy weekend. Will look at it hopefully today.

**Comment by oniony** [comment] 2019-12-02 20:37
@dimgel Sorry, that took me forever. I've moved the fix to the maintenace branch and have pushed v0.7.5.

https://github.com/oniony/TMSU/releases/tag/v0.7.5

**Comment by dimgel** [comment] 2019-12-03 00:58
Thank you! :)
